# Generated by Django 4.0.4 on 2022-05-28 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_admin_user_ban_time_user_user_experience_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='img/'),
        ),
        migrations.DeleteModel(
            name='Admin',
        ),
    ]
