# Generated by Django 4.0.4 on 2022-05-29 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_is_banned'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_login_day',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.FileField(null=True, upload_to='media/img/'),
        ),
    ]
