# Generated by Django 4.0.3 on 2022-06-07 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_user_recent_reply_id_user_rencent_posting_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='rencent_posting_id',
            new_name='recent_posting_id',
        ),
    ]
