# Generated by Django 4.0.3 on 2022-06-08 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_rename_rencent_posting_id_user_recent_posting_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.ImageField(default='img/default_photo.png', upload_to='img/'),
        ),
    ]
