# Generated by Django 4.0.4 on 2022-05-27 14:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Posting',
            fields=[
                ('posting_id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=252)),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=252)),
                ('like_count', models.IntegerField(default=0)),
                ('authority', models.CharField(max_length=60)),
                ('like', models.ManyToManyField(blank=True, related_name='like_posting', to='user.user')),
            ],
        ),
        migrations.CreateModel(
            name='Sector',
            fields=[
                ('sector_name', models.CharField(max_length=60, primary_key=True, serialize=False, unique=True)),
                ('sector_introduction', models.TextField(blank=True, default='暂无简介', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('reply_id', models.AutoField(primary_key=True, serialize=False)),
                ('judge', models.IntegerField()),
                ('content', models.TextField()),
                ('time', models.CharField(max_length=252)),
                ('like_count', models.IntegerField(default=0)),
                ('like', models.ManyToManyField(blank=True, related_name='like_reply', to='user.user')),
                ('posting_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.posting')),
                ('reply1_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to1', to='posting.reply')),
                ('reply2_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reply_to2', to='posting.reply')),
                ('user_id', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
        migrations.AddField(
            model_name='posting',
            name='sector_name',
            field=models.ManyToManyField(to='posting.sector'),
        ),
        migrations.AddField(
            model_name='posting',
            name='user_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user'),
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('file_id', models.AutoField(primary_key=True, serialize=False)),
                ('filename', models.TextField()),
                ('posting_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='posting.posting')),
            ],
        ),
    ]
