# Generated by Django 4.0.4 on 2022-05-28 13:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posting',
            name='sector_name',
        ),
        migrations.AddField(
            model_name='posting',
            name='sector_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.sector'),
        ),
    ]
