# Generated by Django 4.0.4 on 2022-06-06 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0002_remove_posting_sector_name_posting_sector_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='posting',
            name='click_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='posting',
            name='recent_comment_id',
            field=models.IntegerField(default=999999),
        ),
        migrations.AddField(
            model_name='posting',
            name='recent_comment_time',
            field=models.CharField(max_length=252, null=True),
        ),
    ]
