# Generated by Django 4.0.4 on 2022-06-07 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_posting_click_count_posting_recent_comment_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posting',
            name='recent_comment_id',
            field=models.IntegerField(default=-1),
        ),
    ]
