# Generated by Django 4.0.4 on 2022-06-07 23:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0004_alter_posting_recent_comment_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='posting_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='posting.posting'),
        ),
    ]
